# the name of your track or event
name = "Data Transfer"

# the name of the directly responsible individual for this event
# (this person will coordinate with devent organizers)
dri = "Hannah Howard"

# the start date of the event
date = "2022-10-29"

# how many days the event lasts (1 - N)
days = 1

# the event times (shows up in the event card)
#commenting out for now because this track isn't in the schedule
times = "14:00 - 17:30"

# the "difficulty" of the event -- one of:
# ["Beginner", "Intermediate", "Advanced", "All Welcome"]
difficulty = "Advanced"

# tags for the event, will show up as labels.
# pick 1-4
tags = ["Talks"]

# a color, to group key events visually. use sparingly
# color="purple"

# a description of the track.
# will show up when the user clicks the event card.
description = """
  How do IPFS nodes request, send, and receive content? How does data move efficiently across the wire? Let's learn the state of the art in data transfer, and explore directions for future improvements.
"""

# schedule is an array of timeslots objects
# schema:
#  startTime   - string for starting time
#  speakers    - array of string speaker names. please to use consistent naming across timeslots
#  title       - string for talk or timeslot title, should be short
#  description - string describing the timeslot. 1-3 sentences.
# 
# Notes:
# - recommended start: 09:00
# - recommended lunch: 12:00 or 13:00
# - recommended end:   17:00
# - use 15m, 20m, 30m, 45m, or 60m session slots
# - use 15m breaks, one in the morning, one or two in the afternoon
[[timeslots]]
startTime="14:00"
speakers=[]
title="Arrival and welcome"
description=""

[[timeslots]]
startTime="14:15"
speakers=["@hannahhoward"]
title="Track Introduction"
description=""

[[timeslots]]
startTime="14:30"
speakers=["@rangermauve"]
title="What is IPLD Anyway?"
description=""

[[timeslots]]
startTime="15:00"
speakers=[]
title="Break"
description=""

[[timeslots]]
startTime="15:15"
speakers=["@hannahhoward","@willscott"]
title="Data Transfer Tutorial"
description=""

[[timeslots]]
startTime="15:45"
speakers=["@b5"]
title="How Bitswap Works"
description=""

[[timeslots]]
startTime="16:15"
speakers=[]
title="Break"
description=""

[[timeslots]]
startTime="16:30"
speakers=["@Jorropo"]
title="RAPIDE"
description=""

[[timeslots]]
startTime="17:00"
speakers=["@hannahhoward"]
title="The Future Of Content Addressed Data Transfer"
description="Some ideas for massively improving data transfer speed"

[[timeslots]]
startTime="17:15"
speakers=[]
title="Open discussion and wrap-up"
description=""
